version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENV=development
      - PORT=5000
    networks:
      - vecem-network
    volumes:
      - ./Backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - vecem-network
    volumes:
      - ./Frontend:/app
      - /app/node_modules

networks:
  vecem-network:
    driver: bridge
# docker-compose down
# docker-compose build --no-cache
# docker-compose up
